[package]
name = "fm"
version = "0.1.0"
authors = ["Andy Russell <arussell123@gmail.com>"]
edition = "2018"

[dependencies]
argh = "0.1.6"
env_logger = "0.9.0"
gio = "0.14.8"
gtk = "0.14.3"
libdazzle = "0.3.0"
log = "0.4.14"
mime_guess = "2.0.3"
pango = "0.14.8"
pathdiff = "0.2.1"
relm = "0.22.0"
relm-derive = "0.22.0"

[patch.crates-io]
libdazzle = { git = "https://gitlab.gnome.org/euclio/libdazzle-rs.git", branch = "version-update" }

[features]
